package(default_visibility = ["//visibility:public"])

filegroup(
    name = "test_dats",
    srcs = [
        "GALTELA.DAT",
        "MBBSEMU.DAT",
        "MBBSEMU.DB",
        "MBBSEMU.DB.V2",
        "MBMGEPLT.DAT",
        "MULTIACS.DAT",
        "VARIABLE.DAT",
        "WCCACMS2.DAT",
        "WGSMENU2.DAT",
    ],
)
